name: 'CoreWorkflow'
description: 'Generate tags according to core workflow'
#inputs:
#  milliseconds:  # id of input
#    description: 'number of milliseconds to wait'
#    required: true
#    default: '1000'
#outputs:
#  time:
#    description: 'The message to output'
#  new_tag:
#    description: 'Generated tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
