name: Create release candidate tag
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Push RC tag
      uses: arcticfalcon/test-actions@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
