#name: Create tag with new version
#on:
#  push:
#    branches: [ master ]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: '0'
#      - name: Bump version and push tag
#        uses: arcticfalcon/test-actions@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
